### ISSUE TITLE
BUG: Short names as SeverityText

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [pinojs/pino-opentelemetry-transport#153]
It took me some digging to track this down, as I was wondering why there was an enum defined for SeverityNumber but not for SeverityText. Looking through the defined types, SeverityText can be [any string](https://github.com/open-telemetry/opentelemetry-js/blob/63d74cdc366fc337be66c1a766a2cc8e5275a85a/experimental/packages/api-logs/src/types/LogRecord.ts#L71)

From the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/8a78903ef0a1fe7a2056ae4c8c45f9ef10ae9e78/specification/logs/data-model.md#field-severitytext):

> Description: severity text (also known as log level). This is the original string representation of the severity as it is known at the source. If this field is missing and SeverityNumber is present then the _short name_ that corresponds to the SeverityNumber may be used as a substitution. This field is _optional_.

(emphasis added)

It later gives the example:

> For example "Informational" Syslog record will be displayed as INFO (Informational). When for a particular log record the SeverityNumber is defined but the SeverityText is missing it is recommended to only show the short name, e.g. INFO.

So here, Informational appears to be the SeverityText and INFO is the short name.

With this in mind, using a map to retrieve the short name for a given SeverityNumber as the SeverityText seems to not be the intended use of SeverityText. This should likely be configurable.

Using the short names as SeverityText is perfectly fine for my use case right now, and I could be mistaken in my interpretation, but I wanted to flag this for you.

**Comment by Vunovati** [comment]
Hello,

The way we currently set the Short names is recommended but not mandatory.

[Here](https://github.com/open-telemetry/opentelemetry-specification/blob/fc8289b8879f3a37e1eba5b4e445c94e74b20359/specification/logs/data-model.md#displaying-severity) the docs says: _The following table defines the recommended short name for each SeverityNumber value._

I assumed that would be what most package users would want to see. It is true that someone might want to customize this. We could implement this similar to the `severityNumberMap` option.

**Comment by Vunovati** [comment]
@10xLaCroixDrinker Based on the answer to your query in https://github.com/open-telemetry/opentelemetry-specification/issues/3933#issuecomment-1992528154

_SeverityText can be populated with whatever is used by the upstream logging library (if there is one)
["Short name"](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#displaying-severity) is only a recommendation for displaying the severity in backends when SeverityText is missing_


seems like we could (should?) treat this as a bug. It might make sense actually to use the original Pino severity text if available and not translate it. WDYT?

**Comment by 10xLaCroixDrinker** [comment]
That's exactly what I was thinking. I can open a PR that uses the pino log level name as SeverityText
